
services:
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      postgres_db:
        condition: service_started
        restart: true
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: ./app
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      postgres_db:
        condition: service_started
        restart: true
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
  postgres_db:
    image: postgres:latest
    container_name: PostgresDB 
    restart: "no"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres123
    - POSTGRES_DB=db
    ports:
    - '5431:5431'
    volumes:
      - ./db_data:/var/lib/postgresql/data
    # - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
volumes:
  postgres_db:
    driver: local